---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
        - name: grpc-app
          image: grpc-crud-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "postgres://user:password@postgres:5432/crud_db?sslmode=disable"

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-app-service
spec:
  selector:
    app: grpc-app
  type: LoadBalancer
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080









      # For gRPC: kubectl port-forward svc/grpc-app-service 50051:50051
      # For HTTP: kubectl port-forward svc/grpc-app-service 8080:8080