---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE
    );

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "crud_db"
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init-script





#2. Explaining spec: selector: app: postgres
#This is the "Search Filter" for the Service.
#
#A Service is just an IP address; it doesn't actually contain any code. It needs to know which Pods to send traffic to.
#
#How it works: The Service looks at every Pod in your cluster. It asks: "Do you have a label (sticker) that says app=postgres?"
#
#The Result: If it finds a Pod with that sticker, it adds that Pod's IP to its "Active List." When traffic hits the Service, it sends it to one of those matching Pods.